EMarkting/EMarkting/Controllers/User2Controller.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using EMarkting.Models;

namespace EMarkting.Controllers
{
    public class User2Controller : Controller
    {

        private EMarkingTestEntities db;


        public User2Controller()
        {
            db = new EMarkingTestEntities();
        }

        // GET: User2
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult LoginUser()
        {
            if(Session["User_Id"] != null && Session["User_Name"] !=null )
            {
                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpPost]
        public ActionResult LoginUser( User_T user)
        {
            if (ModelState.IsValid)
            {
                var result = db.User_T.Where(x => x.Email == user.Email && x.Password == user.Password).FirstOrDefault();

                Session["User_Id"] = result.Id;
                Session["User_Name"] = result.Name;

                return RedirectToAction("Index");
            }

            return View(user);
        }

      





        [HttpGet]
        public ActionResult SignUp()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(User_T user, HttpPostedFileBase Image)
        {
            string extention = "";

            if (ModelState.IsValid)
            {
                if (user.Image != null)
                {
                    extention = Path.GetExtension(Image.FileName);
                    if (extention.ToLower().Equals(".jpg") || extention.ToLower().Equals(".png") || extention.ToLower().Equals(".jpeg"))
                    {
                        // save PDF in folder
                        string PDFName = Path.GetFileName(Image.FileName);
                        string PDFName2 = DateTime.Now.ToString("yymmss") + PDFName;
                        string physicalPath = Server.MapPath("~/ImgUpload/" + PDFName2);
                        Image.SaveAs(physicalPath);
                        user.Image = PDFName2;
                    }
                    else
                    {
                        ModelState.AddModelError("ImgError", "Error");
                        return View(user);
                    }
                }
                else
                {
                    return View(user);
                }

                db.User_T.Add(user);
                db.SaveChanges();
                return RedirectToAction("LoginUser");

            }

            return View(user);
        }



        [HttpGet]
        public ActionResult CreateProduct()
        {
            if (Session["User_Id"] == null && Session["User_Name"] == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.Cat_id = new SelectList( db.Categories.ToList() , "Id", "Name");
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduct(Product product, HttpPostedFileBase Image)
        {
            string extention = "";
            if (ModelState.IsValid)
            {
                if (product.Image != null)
                {
                    extention = Path.GetExtension(Image.FileName);
                    if (extention.ToLower().Equals(".jpg") || extention.ToLower().Equals(".png") || extention.ToLower().Equals(".jpeg"))
                    {
                        // save PDF in folder
                        string PDFName = Path.GetFileName(Image.FileName);
                        string PDFName2 = DateTime.Now.ToString("yymmss") + PDFName;
                        string physicalPath = Server.MapPath("~/ImgUpload/" + PDFName2);
                        Image.SaveAs(physicalPath);
                        product.Image = PDFName2;
                    }
                    else
                    {
                        ModelState.AddModelError("ImgError", "Error");
                        ViewBag.Cat_id = new SelectList(db.Categories.ToList(), "Id", "Name",product.Cat_id);
                        return View(product);
                    }
                }
                else
                {
                    return View(product);
                }
                product.User_id = Convert.ToInt32(Session["User_Id"].ToString());
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cat_id = new SelectList(db.Categories.ToList(), "Id", "Name", product.Cat_id);
            return View(product);
        }







        public ActionResult CategoriesList()
        {
            if ( Session["User_Id"] == null && Session["User_Name"] == null )
            {
                return RedirectToAction("Index");
            }
            var result = db.Categories.ToList();
            return View(result);
        }



        public ActionResult ProductList()
        {
            if (Session["User_Id"] == null && Session["User_Name"] == null)
            {
                return RedirectToAction("Index");
            }
            var result = db.Products.ToList();
            return View(result);
        }


        public ActionResult DeleteProduct(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("ProductList");
            }

            var Result = db.Products.Find(id);

            db.Products.Remove(Result);
            db.SaveChanges();
            Thread.Sleep(2000);
            return RedirectToAction("ProductList");
        }




    }
}

EMarkting/EMarkting/Views/User2/CategoriesList.cshtml
@model IEnumerable<EMarkting.Models.Category>

@{
    ViewBag.Title = "CategoriesList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CategoriesList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
     


    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
           <img src="~/ImgUpload/@item.Image"  style="width:30px; height:30px;"  />
        </td>
  
       
    </tr>
}

</table>

EMarkting/EMarkting/Views/User2/CreateProduct.cshtml
@model EMarkting.Models.Product

@{
    ViewBag.Title = "CreateProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateProduct</h2>

@using (Html.BeginForm("CreateProduct", "User2", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image,   new { @type="file", @id= "Image", @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cat_id, "Cat_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cat_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cat_id, "", new { @class = "text-danger" })
            </div>
        </div>

 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EMarkting/EMarkting/Views/User2/LoginUser.cshtml
@model EMarkting.Models.User_T

@{
    ViewBag.Title = "LoginUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LoginUser</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User_T</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
  

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EMarkting/EMarkting/Views/User2/ProductList.cshtml
@model IEnumerable<EMarkting.Models.Product>

@{
    ViewBag.Title = "ProductList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ProductList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.User_T.Name)
        </th>
        <th>  </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
           <img src="~/ImgUpload/@item.Image"   style="width:30px;height:30px;" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.User_T.Name)
        </td>
        <td >@Html.ActionLink("Delete", "Delete", new { id = @item.Id }) </td>

    </tr>
}

</table>

EMarkting/EMarkting/Views/User2/SignUp.cshtml
@model EMarkting.Models.User_T

@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SignUp</h2>

@using (Html.BeginForm("SignUp","User2", FormMethod.Post , new { enctype="multipart/form-data"  }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User_T</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image, new { @type="file" ,@id= "Image", @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>