EMarkting/EMarkting/Controllers/Admin2Controller.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EMarkting.Models;
using PagedList;

namespace EMarkting.Controllers
{
    public class Admin2Controller : Controller
    {
        private EMarkingTestEntities db;

        public Admin2Controller()
        {
            db = new EMarkingTestEntities();
        }

        public ActionResult Login()
        {
            if(Session["Admin_Id"] !=null  && Session["Admin_Name"] !=null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public  ActionResult  Login(Admin admin)
        {
            if(ModelState.IsValid)
            {

                var result = db.Admins.Where(x => x.UserName == admin.UserName && x.Password == admin.Password).FirstOrDefault();
                if(result !=null)
                {
                    Session["Admin_Id"] = result.id;
                    Session["Admin_Name"] = result.UserName;
                    return RedirectToAction("Index");

                }
            }

            return View(admin);
        }


        [HttpGet]
        public ActionResult CreateCategory()
        {
            if(Session["Admin_Id"] ==null &&  Session["Admin_Name"] == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(Category category , HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                var extention = "";
                if (category.Image != null)
                {
                    extention = Path.GetExtension(Image.FileName);
                    if (extention.ToLower().Equals(".jpg") || extention.ToLower().Equals(".png") || extention.ToLower().Equals(".jpeg"))
                    {
                        // save Image in folder
                        string PDFName = Path.GetFileName(Image.FileName);
                        string PDFName2 = DateTime.Now.ToString("yymmss") + PDFName;
                        string physicalPath = Server.MapPath("~/ImgUpload/" + PDFName2);
                        Image.SaveAs(physicalPath);
                        category.Image = PDFName2;
                    }
                    else
                    {
                        ModelState.AddModelError("ImgError", "Error");
                        return View(category);
                    }
                }
                else
                {
                    return View(category);
                }
                category.Admin_Id =  Convert.ToInt32( Session["Admin_Id"].ToString() );
                category.Status = true;
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }



        public ActionResult ViewAllCategory(int? page )
        {

            if (Session["Admin_Id"] == null && Session["Admin_Name"] == null)
            {
                return RedirectToAction("Login");
            }

            var result = db.Categories.ToList().ToPagedList(page ?? 1, 3) ;

            return View(result);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("ViewCategory");
            }

            var Result = db.Categories.Find(id);

            db.Categories.Remove(Result);
            db.SaveChanges();
            Thread.Sleep(2000);
            return RedirectToAction("ViewAllCategory");
        }




        public ActionResult LogOut()
        {
            Session.RemoveAll();
            Session.Abandon();
            Thread.Sleep(2000);
            return RedirectToAction("Index");
        }

    }
}

EMarkting/EMarkting/Views/Admin2/CreateCategory.cshtml
@model EMarkting.Models.Category

@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateCategory</h2>

@using (Html.BeginForm("CreateCategory","Admin2",FormMethod.Post , new {  enctype= "multipart/form-data" }  ))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Category</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

  


    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Image, new { type = "file", id = "Image", @class = "form-control" })
            @*@Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            @Html.ValidationMessage("ImgError", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EMarkting/EMarkting/Views/Admin2/Login.cshtml
@model EMarkting.Models.Admin

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
 

EMarkting/EMarkting/Views/Admin2/ViewAllCategory.cshtml
@*@model IEnumerable<EMarkting.Models.Category>*@

@{
    ViewBag.Title = "ViewAllCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ViewAllCategory</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Image
        </th>
        <th>
            Status
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="~/ImgUpload/@item.Image" style=" height:20px;width:20px;border-radius:5px" />

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>

            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EMarkting.Models.Category>



@Html.PagedListPager(Model, Page => Url.Action("ViewCategory", new
{ Page }), new PagedListRenderOptions()
{
    Display = PagedListDisplayMode.IfNeeded,
    DisplayPageCountAndCurrentLocation = true
})