EMarkting/EMarkting/Controllers/UserConController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using EMarkting.Models;
using PagedList;

namespace EMarkting.Controllers
{
    public class UserConController : Controller
    {

        private EMarkingTestEntities db = new EMarkingTestEntities();


        public ActionResult Index(int ? page)
        {
           


            return View(db.Categories.ToList().OrderByDescending(x=>x.Id).ToPagedList(page ?? 1, 9));
        }

        [HttpGet]
        public ActionResult SignUp()
        {
            if(Session["User_Id"] !=null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        
        [HttpPost]
        public ActionResult SignUp(User_T user,HttpPostedFileBase Image)
        {
            string extention = "";
            if (ModelState.IsValid)
            {
                user.Password =
                    FormsAuthentication.HashPasswordForStoringInConfigFile(user.Password, "SHA1");
                
                if (user.Image != null)
                {
                    extention = Path.GetExtension(Image.FileName);
                    if (extention.ToLower().Equals(".jpg") || extention.ToLower().Equals(".png") || extention.ToLower().Equals(".jpeg"))
                    {
                        // save PDF in folder
                        string PDFName = Path.GetFileName(Image.FileName);
                        string PDFName2 = DateTime.Now.ToString("yymmss") + PDFName;
                        string physicalPath = Server.MapPath("~/ImgUpload/" + PDFName2);
                        Image.SaveAs(physicalPath);
                        user.Image = PDFName2;
                    }
                    else
                    {
                        ModelState.AddModelError("ImgError", "Error");
                        return View(user);
                    }
                }
                else
                {
                    return View(user);
                }


                db.User_T.Add(user);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(user);
        }

        // login
        [HttpGet]
        public ActionResult Login()
        {
            if (Session["User_Id"] != null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Login(User_T user)
        {
         
            if (ModelState.IsValid)
            { 
                var newPass =
             FormsAuthentication.HashPasswordForStoringInConfigFile(user.Password, "SHA1");
            var val = db.User_T.Where(x => x.Email == user.Email && x.Password == newPass).FirstOrDefault();
                if(val !=null)
                {
                    Session["User_Id"] = val.Id;
                    return RedirectToAction("CreateAds");
                }

            }
            return View(user);
        }

        [HttpGet]
        public ActionResult CreateAds()
        {
            if (Session["User_Id"] == null)
            {
                return RedirectToAction("Login");
            }
            ViewBag.Cat_id = new SelectList(db.Categories.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult CreateAds(Product product, HttpPostedFileBase Image)
        {
            string extention = "";
            if (ModelState.IsValid)
            {
                if (product.Image != null)
                {
                    extention = Path.GetExtension(Image.FileName);
                    if (extention.ToLower().Equals(".jpg") || extention.ToLower().Equals(".png") || extention.ToLower().Equals(".jpeg"))
                    {
                        // save PDF in folder
                        string PDFName = Path.GetFileName(Image.FileName);
                        string PDFName2 = DateTime.Now.ToString("yymmss") + PDFName;
                        string physicalPath = Server.MapPath("~/ImgUpload/" + PDFName2);
                        Image.SaveAs(physicalPath);
                        product.Image = PDFName2;
                    }
                    else
                    {
                        ModelState.AddModelError("ImgError", "Error");
                        return View(product);
                    }
                }
                else
                {
                    return View(product);
                }
                product.User_id =Convert.ToInt32(Session["User_Id"]);

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("index");
            }

            ViewBag.Cat_id = new SelectList(db.Categories.ToList(), "Id", "Name");
            return View(product);
        }

        // ads All Ads For This Category
        public ActionResult Ads(int ? id)
        {
            if (Session["User_Id"] == null)
            {
                return RedirectToAction("Index");
            }
            return View(db.Products.Where(x => x.Cat_id == id).ToList());
        }
 
        // view jsut one ads
        public ActionResult AdSpecfic(int id)
        {

            var prodct = db.Products.Where(x => x.Id == id).FirstOrDefault();
            var category = db.Categories.Where(x => x.Id == prodct.Cat_id).FirstOrDefault();
            var User = db.User_T.Where(x => x.Id == prodct.User_id).FirstOrDefault();

            ViewSpecifVM vM = new ViewSpecifVM();
            // product
            vM.Id_Product = prodct.Id;
            vM.Name_Product = prodct.Name;
            vM.Image_Product = prodct.Name;
            vM.Price_Product = prodct.Price;
            vM.Description_Product = prodct.Description;

            // category
            vM.Name_Category = category.Name;

            // user
            vM.Name_User = User.Name;
            vM.Image_User = User.Image;
            vM.Contact_User = User.Contact;

            return View(vM);
        }


        public ActionResult DeleteAd(string id)
        {
            if(Session["User_Id"] ==null)
            {
                return RedirectToAction("Index");
            }
            if(id==null)
            {
                return RedirectToAction("Index");
            }
            var val = db.Products.Where(x => x.Id == Convert.ToInt32(id)).FirstOrDefault();
            db.Products.Remove(val);
            db.SaveChanges();
            return View("Index");
        }


        public ActionResult SignOut()
        {
            Session.RemoveAll();
            Session.Abandon();
            return RedirectToAction("Index");
        }



    }
}

EMarkting/EMarkting/Views/UserCon/AdSpecfic.cshtml
@model EMarkting.Models.ViewSpecifVM

@{
    ViewBag.Title = "AdSpecfic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdSpecfic</h2>

<div>
    <h4>ViewSpecifVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id_Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name_Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description_Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description_Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price_Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price_Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cat_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cat_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name_Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name_User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_User)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_User)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Image_User)*@
            <img src="~/ImgUpload/@Model.Image_User" style="width:100px;height:100px" />
        </dd>

        <dd>
         @if(Convert.ToInt32(Session["User_Id"])  == Convert.ToInt32( Model.User_id) )
         {
            <input type="submit"  value="Delete" class="" />
            @Html.ActionLink("Delete", "DeleteAd", "UserCon",new { id = Model.User_id} ,new { @class= "btn btn-danger" })
         }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_User)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

EMarkting/EMarkting/Views/UserCon/Ads.cshtml
@model IEnumerable<EMarkting.Models.Product>

@{
    ViewBag.Title = "Ads";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ads</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User_T.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            
            <img src="~/ImgUpload/@item.Image"  width="40px" height="40px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User_T.Name)
        </td>
        <td>
            @Html.ActionLink("View It ", "AdSpecfic", "UserCon",new { id=item.Id }, new { @class=""}) 

        </td>
    </tr>
}

</table>

EMarkting/EMarkting/Views/UserCon/CreateAds.cshtml
@model EMarkting.Models.Product

@{
    ViewBag.Title = "CreateAds";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> CreateAds  " Product " </h2>

@using (Html.BeginForm("CreateAds", "UserCon", FormMethod.Post, new { enctype = "multipart/form-data" } ))
{
        @Html.AntiForgeryToken()
         <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Image, new { type = "file", id = "Image", @class = "form-control" })
                @*@Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
                @Html.ValidationMessage("ImgError", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cat_id, "Cat_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cat_id", null,"------", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cat_id, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.User_id, "User_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("User_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

EMarkting/EMarkting/Views/UserCon/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<EMarkting.Models.Category>
 
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View  Category</title>
    <link href="~/Content/paginition.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <script>
        alert("admin  email:  admin ,, pas:admin  ");
        alert("user  email:  eslam ,, pas:eslam  ");
    </script>
</head>
<body>
    <div class="container">
        @*style="height:1150px; "*@

        @*<div class="row">
            <div class="col-lg-12" style="height:100px; border:1px solid solid; ">
                <img src="~/Content/img/Modern-e-Commerce-Web-Design-Trends.-Part-2.gif" style="width:100%; height:100%" />
            </div>
        </div>*@



        <div class="row" style="margin-bottom:40px">
            @if (Model != null)
        {
            foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-4" style="height:200px;margin-top:100px">
                    <img src="~/ImgUpload/@item.Image" style=" height:100%;width:100% ;border-radius:50px 50px 50px 50px" />
                    <h4 style="color:#808080; font-family:'Arial Rounded MT';text-align:center">@Html.ActionLink(@item.Name, "Ads", new { id = @item.Id })  </h4>
                </div>

        }
    }
        </div>
    </div>

    @Html.PagedListPager(Model, Page => Url.Action("ViewCategory", new
    { Page }), new PagedListRenderOptions()
    {
        Display = PagedListDisplayMode.IfNeeded,
        DisplayPageCountAndCurrentLocation = true
    })

</body>
</html>

EMarkting/EMarkting/Views/UserCon/Login.cshtml
@model EMarkting.Models.User_T

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> Login User </h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<p>
    @Html.ActionLink("Register Now", "SignUp", "UserCon")

</p>

EMarkting/EMarkting/Views/UserCon/SignUp.cshtml
@model EMarkting.Models.User_T

@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SignUp</h2>

@using (Html.BeginForm("SignUp", "UserCon", FormMethod.Post , new { enctype = "multipart/form-data" } ))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User_T</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Image, new { type = "file", id = "Image", @class = "form-control" })
                @*@Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
                @Html.ValidationMessage("ImgError", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>